# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\lutom\Desktop\GitHub\xolra-continued

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\lutom\Desktop\GitHub\xolra-continued

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\lutom\Desktop\GitHub\xolra-continued\CMakeFiles C:\Users\lutom\Desktop\GitHub\xolra-continued\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\lutom\Desktop\GitHub\xolra-continued\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Xolra

# Build rule for target.
Xolra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Xolra
.PHONY : Xolra

# fast build rule for target.
Xolra/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/build
.PHONY : Xolra/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\run.dir\build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/AssetManager.obj: src/AssetManager.cpp.obj
.PHONY : src/AssetManager.obj

# target to build an object file
src/AssetManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/AssetManager.cpp.obj
.PHONY : src/AssetManager.cpp.obj

src/AssetManager.i: src/AssetManager.cpp.i
.PHONY : src/AssetManager.i

# target to preprocess a source file
src/AssetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/AssetManager.cpp.i
.PHONY : src/AssetManager.cpp.i

src/AssetManager.s: src/AssetManager.cpp.s
.PHONY : src/AssetManager.s

# target to generate assembly for a file
src/AssetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/AssetManager.cpp.s
.PHONY : src/AssetManager.cpp.s

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Enemy.obj: src/Enemy.cpp.obj
.PHONY : src/Enemy.obj

# target to build an object file
src/Enemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Enemy.cpp.obj
.PHONY : src/Enemy.cpp.obj

src/Enemy.i: src/Enemy.cpp.i
.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s
.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/Game.obj: src/Game.cpp.obj
.PHONY : src/Game.obj

# target to build an object file
src/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Game.cpp.obj
.PHONY : src/Game.cpp.obj

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Hud.obj: src/Hud.cpp.obj
.PHONY : src/Hud.obj

# target to build an object file
src/Hud.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Hud.cpp.obj
.PHONY : src/Hud.cpp.obj

src/Hud.i: src/Hud.cpp.i
.PHONY : src/Hud.i

# target to preprocess a source file
src/Hud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Hud.cpp.i
.PHONY : src/Hud.cpp.i

src/Hud.s: src/Hud.cpp.s
.PHONY : src/Hud.s

# target to generate assembly for a file
src/Hud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Hud.cpp.s
.PHONY : src/Hud.cpp.s

src/Item.obj: src/Item.cpp.obj
.PHONY : src/Item.obj

# target to build an object file
src/Item.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Item.cpp.obj
.PHONY : src/Item.cpp.obj

src/Item.i: src/Item.cpp.i
.PHONY : src/Item.i

# target to preprocess a source file
src/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Item.cpp.i
.PHONY : src/Item.cpp.i

src/Item.s: src/Item.cpp.s
.PHONY : src/Item.s

# target to generate assembly for a file
src/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Item.cpp.s
.PHONY : src/Item.cpp.s

src/Particle.obj: src/Particle.cpp.obj
.PHONY : src/Particle.obj

# target to build an object file
src/Particle.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Particle.cpp.obj
.PHONY : src/Particle.cpp.obj

src/Particle.i: src/Particle.cpp.i
.PHONY : src/Particle.i

# target to preprocess a source file
src/Particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Particle.cpp.i
.PHONY : src/Particle.cpp.i

src/Particle.s: src/Particle.cpp.s
.PHONY : src/Particle.s

# target to generate assembly for a file
src/Particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Particle.cpp.s
.PHONY : src/Particle.cpp.s

src/Pet.obj: src/Pet.cpp.obj
.PHONY : src/Pet.obj

# target to build an object file
src/Pet.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Pet.cpp.obj
.PHONY : src/Pet.cpp.obj

src/Pet.i: src/Pet.cpp.i
.PHONY : src/Pet.i

# target to preprocess a source file
src/Pet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Pet.cpp.i
.PHONY : src/Pet.cpp.i

src/Pet.s: src/Pet.cpp.s
.PHONY : src/Pet.s

# target to generate assembly for a file
src/Pet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Pet.cpp.s
.PHONY : src/Pet.cpp.s

src/Player.obj: src/Player.cpp.obj
.PHONY : src/Player.obj

# target to build an object file
src/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Player.cpp.obj
.PHONY : src/Player.cpp.obj

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Projectile.obj: src/Projectile.cpp.obj
.PHONY : src/Projectile.obj

# target to build an object file
src/Projectile.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Projectile.cpp.obj
.PHONY : src/Projectile.cpp.obj

src/Projectile.i: src/Projectile.cpp.i
.PHONY : src/Projectile.i

# target to preprocess a source file
src/Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Projectile.cpp.i
.PHONY : src/Projectile.cpp.i

src/Projectile.s: src/Projectile.cpp.s
.PHONY : src/Projectile.s

# target to generate assembly for a file
src/Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/Projectile.cpp.s
.PHONY : src/Projectile.cpp.s

src/World.obj: src/World.cpp.obj
.PHONY : src/World.obj

# target to build an object file
src/World.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/World.cpp.obj
.PHONY : src/World.cpp.obj

src/World.i: src/World.cpp.i
.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s
.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Xolra.dir\build.make CMakeFiles/Xolra.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... run
	@echo ... Xolra
	@echo ... src/AssetManager.obj
	@echo ... src/AssetManager.i
	@echo ... src/AssetManager.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Enemy.obj
	@echo ... src/Enemy.i
	@echo ... src/Enemy.s
	@echo ... src/Game.obj
	@echo ... src/Game.i
	@echo ... src/Game.s
	@echo ... src/Hud.obj
	@echo ... src/Hud.i
	@echo ... src/Hud.s
	@echo ... src/Item.obj
	@echo ... src/Item.i
	@echo ... src/Item.s
	@echo ... src/Particle.obj
	@echo ... src/Particle.i
	@echo ... src/Particle.s
	@echo ... src/Pet.obj
	@echo ... src/Pet.i
	@echo ... src/Pet.s
	@echo ... src/Player.obj
	@echo ... src/Player.i
	@echo ... src/Player.s
	@echo ... src/Projectile.obj
	@echo ... src/Projectile.i
	@echo ... src/Projectile.s
	@echo ... src/World.obj
	@echo ... src/World.i
	@echo ... src/World.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

